In [ ]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)
print(type(x))
print(x.ndim)

In [ ]:
import numpy as np   
l=[]
for i in range(1,6):
    int_l=int(input("enter:"))
    l.append(int_l)
    print(np.array(l))

In [1]:
import numpy as np 
y=np.array([[1,2,3,4],[2,3,67,8]])
print(y)
print(y.ndim)

[[ 1  2  3  4]
 [ 2  3 67  8]]
2


In [7]:
import numpy as np
y=np.array([1,2,3,4],ndmin=10)
print(y)
print(y.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [12]:
import numpy as np
ar_zero=np.zeros(4)
print(ar_zero)
ar_zero2=np.zeros((2,3))
print(ar_zero2)

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
import numpy as np
ar_rn=np.arange(24)
print(ar_rn)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [16]:
ar_dia=np.eye(4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
import numpy as np
ar_lin=np.linspace(1,10,num=5)
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]


In [20]:
import numpy as np
var=np.random.rand(4)
print(var)

[0.41683878 0.7740848  0.67541181 0.21016891]


In [21]:
import numpy as np
var=np.random.rand(4,5)
print(var)

[[0.41777394 0.54193058 0.90678443 0.89932447 0.40740474]
 [0.83625736 0.35625595 0.75169248 0.91624551 0.68097378]
 [0.76941388 0.76114803 0.04629971 0.14874273 0.78295366]
 [0.1992134  0.6961799  0.95492228 0.15931517 0.05544853]]


In [22]:
import numpy as np
var=np.random.randn(4,5)
print(var)

[[-0.37204382 -0.20730239  1.16479536  0.0220162  -1.87609191]
 [ 1.58130266  0.54014653  1.83309899 -0.46285361  1.09442623]
 [-0.25028874  0.93631355 -0.95883941 -0.62752136  0.99678281]
 [-0.84979498  0.02373316 -0.03829961  0.88866095  0.08861435]]


In [24]:
import numpy as np
var=np.random.ranf(5)
print(var)

[0.97290926 0.93237462 0.47915471 0.1196991  0.90481511]


In [30]:
import numpy as np
ar_ram=np.random.randint(1,10,5)
print(ar_ram)

[6 4 5 6 3]


In [31]:
import numpy as np
ar_ram=np.array([1,10,5])
print("Dta type:",ar_ram.dtype)

Dta type: int64


In [33]:
import numpy as np
ar_ram=np.array([[1,10,5],[1,2,3]])
print(ar_ram.shape)

(2, 3)


In [38]:
import numpy as np
ar_ram=np.array([1,10,51,2,3,4])
x=ar_ram.reshape(3,2)
print(x)

[[ 1 10]
 [51  2]
 [ 3  4]]


In [39]:
import numpy as np
ar_ram=np.array([1,10,51,2,3,4])
var_add=ar_ram+3
print(var_add)

[ 4 13 54  5  6  7]


In [44]:
import numpy as np
ar_ram=np.array([1,10,51,2,3,4])
var_add=np.add(ar_ram,3)
print(var_add)

[ 4 13 54  5  6  7]


In [40]:
import numpy as np
ar_ram=np.array([1,10,51,2,3,4])
ram_2=([2,3,4,5,6,7])
var_add=ar_ram+ram_2
print(var_add)

[ 3 13 55  7  9 11]


In [43]:
import numpy as np
ar_ram=np.array([1,10,51,2,3,4])
ram_2=([2,3,4,5,6,7])
var_add=np.add(ar_ram,ram_2)
print(var_add)

[ 3 13 55  7  9 11]


In [41]:
import numpy as np
ar_ram=np.array([1,10,51,2,3,4])
var_multi=ar_ram/3
print(var_multi)

[ 0.33333333  3.33333333 17.          0.66666667  1.          1.33333333]


In [42]:
import numpy as np
ar_ram=np.array([1,10,51,2,3,4])
var_multi=ar_ram%3
print(var_multi)

[1 1 0 2 0 1]


In [46]:
import numpy as np
ar_ram=np.array([1,10,51,2,3,4])
var_pow=ar_ram**3
print(var_pow)

[     1   1000 132651      8     27     64]


In [48]:
import numpy as np
ar_ram=np.array([[1,10,51,2,3,4],[2,3,4,5,6,7]])
var_mar=([[2,3,4,78,90,89],[23,5,467,98,79,54]])
var_add=np.add(ar_ram,var_mar)
print(var_add)

[[  3  13  55  80  93  93]
 [ 25   8 471 103  85  61]]


In [51]:
import numpy as np
ar_ram=np.array([1,10,51,2,3,4])
var_min=np.min(ar_ram)
print(var_min)
print("max:",np.max(ar_ram))

1
max: 51


In [52]:
import numpy as np
ar_ram=np.array([1,10,51,2,3,4])
var_min=np.min(ar_ram)
print(var_min)
print("max:",np.max(ar_ram),np.argmax(ar_ram))

1
max: 51 2


In [63]:
import numpy as np
ar_ram=np.array([1,10,51,2,3,4])
var_sqrt=np.sqrt(ar_ram)
print(var_sqrt)


[1.         3.16227766 7.14142843 1.41421356 1.73205081 2.        ]


In [66]:
import numpy as np
ar_ram=np.array([1,10,51,2,3,4])
var_trigno=np.cos(ar_ram)
print(var_trigno)
print(np.cumsum(ar_ram))

[ 0.54030231 -0.83907153  0.7421542  -0.41614684 -0.9899925  -0.65364362]
[ 1 11 62 64 67 71]


In [70]:
import numpy as np
ar_ram=np.array([1,10,51,2,3,4])
print(ar_ram[-5])


10


In [74]:
var1=np.array([[1,2,3,4,5],[34,56,78,90,1]])
print(var1.ndim)
print(var1[1,-3])

2
78


In [76]:
var1=np.array([[[1,2,3,4,5],[34,56,78,90,1]]])
print(var1.ndim)
print(var1[0,1,-3])


3
78


In [88]:
var1=np.array([1,2,3,4,5,34,56,78,90,11])
print(var1[1:11:2])



[ 2  4 34 78 11]


In [90]:
var1=np.array([[1,2,3,4,5],[34,56,78,90,1]])
print(var1[1,1:56:2])


[56 90]


In [3]:
import numpy as np
var1=np.array([1,2,3,4,5,34,56,78,90,11])
for i in var1:
    print(i)

1
2
3
4
5
34
56
78
90
11


In [9]:
import numpy as np
var1=np.array([[1,2,3,4,5],[34,56,78,90,11]])
for i in var1:
     for l in i:
      print(l)

1
2
3
4
5
34
56
78
90
11


In [10]:
import numpy as np
var1=np.array([[[1,2,3,4,5],[34,56,78,90,11]]])
for i in var1:
     for l in i:
       for j in l:
        print(j)

1
2
3
4
5
34
56
78
90
11


In [12]:
import numpy as np
var1=np.array([[[1,2,3,4,5],[34,56,78,90,11]]])
for i in np.nditer(var1):
    print(i)


1
2
3
4
5
34
56
78
90
11


In [13]:
import numpy as np
var1=np.array([[[1,2,3,4,5],[34,56,78,90,11]]])
for i,d in np.ndenumerate(var1):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 34
(0, 1, 1) 56
(0, 1, 2) 78
(0, 1, 3) 90
(0, 1, 4) 11


In [23]:
import numpy as np
var1=np.array([1,2,3,4,5])
var3=np.array([1,45,65,78,90])
var2= np.concatenate((var1,var3))
print(var2)

[ 1  2  3  4  5  1 45 65 78 90]


In [25]:
import numpy as np
var1=np.array([[1,2],[4,5]])
var3=np.array([[1,45],[78,90]])
var2= np.concatenate((var1,var3),axis=1)
print(var2)

[[ 1  2  1 45]
 [ 4  5 78 90]]


In [27]:
import numpy as np
var1=np.array([[1,2],[4,5]])
var3=np.array([[1,45],[78,90]])
var2= np.stack((var1,var3),axis=1)
print(var2)

[[[ 1  2]
  [ 1 45]]

 [[ 4  5]
  [78 90]]]


In [29]:
import numpy as np
var1=np.array([[1,2],[4,5]])
var3=np.array([[1,45],[78,90]])
var2= np.hstack((var1,var3))
print(var2)

[[ 1  2  1 45]
 [ 4  5 78 90]]


In [30]:
import numpy as np
var1=np.array([[1,2],[4,5]])
var3=np.array([[1,45],[78,90]])
var2= np.vstack((var1,var3))
print(var2)

[[ 1  2]
 [ 4  5]
 [ 1 45]
 [78 90]]


In [31]:
import numpy as np
var1=np.array([[1,2],[4,5]])
var3=np.array([[1,45],[78,90]])
var2= np.dstack((var1,var3))
print(var2)

[[[ 1  1]
  [ 2 45]]

 [[ 4 78]
  [ 5 90]]]


In [35]:
import numpy as np
var1=np.array([1,2,3,4,5,6])
var2= np.split(var1,3)
print(var2)
print(var1[0])

[array([1, 2]), array([3, 4]), array([5, 6])]
1


In [40]:
import numpy as np
var1=np.array([1,2,3,4,5,6])
x=np.where((var1/2)==2)
print(x)

(array([3]),)


In [42]:
import numpy as np
var1=np.array([1,2,3,4,5,6])
x=np.searchsorted(var1,5)
print(x)

4


In [45]:
import numpy as np
var1=np.array([1,2,3,4,5,6])
x=np.searchsorted(var1,7,side='right')
print(x)

6


In [46]:
import numpy as np
var1=np.array([1,2,3,4,5,6])
x=np.searchsorted(var1,[4,4,4],side='right')
print(x)

[4 4 4]
